title: kppb
description: >-
  kbertalan's personal programming blog
author: kbertalan
baseurl: ""
url: "kbertalan.github.io"
twitter_username: "#kbertalan"
github_username:  kbertalan

github:
  is_project_page: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme


exclude:
  - docker-compose.yml
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
